version: '3.8'

services:
  api:
    restart: unless-stopped
    build: .
    ports:
      - "3400:3000"
    environment:
      - PORT=3000
      # change based on your db settings below (postgres:postgres -> username:password)
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookbug?schema=public
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: sh -c "npx prisma migrate deploy && npm start"

  db:
    restart: unless-stopped
    image: postgres:15
    ports:
      - "3401:5432"
    environment:
      - POSTGRES_USER=postgres # username (need change)
      - POSTGRES_PASSWORD=postgres # password (need change)
      - POSTGRES_DB=bookbug
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 